version: '2'
services:
      webserver:
        container_name: bumd
        volumes:
             - .:/var/www/app
        links:
             - db
        build:
           context: .
           dockerfile: Dockerfile
        ports:
             - 5002:80

      db:
        image: mariadb:latest
        container_name: db_class
        volumes:
             - ./data/mysql-data:/var/lib/mysql
        environment:
             - MYSQL_ROOT_PASSWORD=class123@
             - MYSQL_USER=class_user
             - MYSQL_PASSWORD=class123@
             - MYSQL_DATABASE=class_db
